# Mod properties
mod_name=Radical Cobblemon Trainers API
mod_id=rctapi
mod_author=HDainester
mod_version=0.9.1-beta
mod_description=Trainer management and battle API for Cobblemon.
maven_group=com.gitlab.srcmc
license=GNU-LGPL-3
enabled_platforms=fabric,neoforge

# Minecraft properties
minecraft_version=1.21.1

# Dependencies
architectury_api_version=13.0.2

fabric_loader_version=0.16.5
fabric_api_version=0.105.0+1.21.1

neoforge_version=21.1.65
neoforge_loader_version=4
neoforge_min_version=21.1

kotlin_stdlib_version=2.0.0
kotlin_for_forge_version=5.4.0
cobblemon_version=1.6.0+1.21.1-SNAPSHOT

## Gradle
org.gradle.jvmargs=-Xmx3G
org.gradle.daemon=false
org.gradle.parallel=true
org.gradle.java.home=/Program Files/Java/jdk-21.0.4+7
