/*
 * This file is part of Radical Cobblemon Trainers API.
 * Copyright (c) 2025, HDainester, All rights reserved.
 *
 * Radical Cobblemon Trainers API is free software: you can redistribute it and/or modify
 * it under the terms of the GNU Lesser General Public License as published by
 * the Free Software Foundation, either version 3 of the License, or
 * (at your option) any later version.
 *
 * Radical Cobblemon Trainers API is distributed in the hope that it will be useful, but
 * WITHOUT ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or
 * FITNESS FOR A PARTICULAR PURPOSE. See the GNU Lesser General Public License for
 * more details.
 *
 * You should have received a copy of the GNU Lesser General Public License along
 * with Radical Cobblemon Trainers API. If not, see <http://www.gnu.org/licenses/lgpl>.
 */
package com.gitlab.srcmc.rctapi.api.ai.utils;

import java.util.Map;

import com.cobblemon.mod.common.api.moves.Move;
import com.cobblemon.mod.common.api.moves.categories.DamageCategories;
import com.cobblemon.mod.common.battles.InBattleMove;
import com.cobblemon.mod.common.battles.pokemon.BattlePokemon;

public enum MoveType {
    DAMAGE, STATUS, HEAL, CURE, BUFF, MALUS;

    public interface Evaluator {
        double eval(BattlePokemon from, BattlePokemon to, Object move);
    }

    public interface Handler {
        void handle(BattlePokemon from, BattlePokemon to);
    }

    public static MoveType of(InBattleMove move) {
        return of(TypeChart.getMove(move));
    }

    public static MoveType of(Move move) {
        var mt = MOVE_TYPES.get(move.getName());

        return mt == null
            ? (DamageCategories.INSTANCE.getSTATUS().getName().equals(move.getDamageCategory().getName())
                ? STATUS
                : DAMAGE) : mt;
    }

    public static double eval(BattlePokemon from, BattlePokemon to, String moveId) {
        return MOVE_EVALUATORS.getOrDefault(moveId, (f, t, m) -> 1.0).eval(from, to, null);
    }

    public static void handle(String moveId, BattlePokemon from, BattlePokemon to) {
        MOVE_HANDLERS.getOrDefault(moveId, (f, t) -> {}).handle(from, to);
    }

    private static boolean ability(BattlePokemon p, String... names) {
        var a = p.getEffectedPokemon().getAbility().getName();

        for(var n : names) {
            if(a.equals(n)) {
                return true;
            }
        }

        return false;
    }

    // custom move evaluations
    private static final Map<String, Evaluator> MOVE_EVALUATORS = Map.<String, Evaluator>ofEntries(
        Map.<String, Evaluator>entry("attract", (from, to, move) -> BattleEffects.Pokemon.Volatile.attract(to) ? 0.0 : 1.0),
        Map.<String, Evaluator>entry("confuseray", (from, to, move) -> (BattleEffects.Pokemon.Volatile.confusion(to) || (!BattleEffects.Pokemon.State.raised(to) && BattleEffects.Field.Terrain.mistyterrain(to))) ? 0.0 : 1.0),
        Map.<String, Evaluator>entry("flatter", (from, to, move) -> (BattleEffects.Pokemon.Volatile.confusion(to) || (!BattleEffects.Pokemon.State.raised(to) && BattleEffects.Field.Terrain.mistyterrain(to))) ? 0.0 : 1.0),
        Map.<String, Evaluator>entry("supersonic", (from, to, move) -> (BattleEffects.Pokemon.Volatile.confusion(to) || (!BattleEffects.Pokemon.State.raised(to) && BattleEffects.Field.Terrain.mistyterrain(to))) ? 0.0 : 1.0),
        Map.<String, Evaluator>entry("swagger", (from, to, move) -> (BattleEffects.Pokemon.Volatile.confusion(to) || (!BattleEffects.Pokemon.State.raised(to) && BattleEffects.Field.Terrain.mistyterrain(to))) ? 0.0 : 1.0),
        Map.<String, Evaluator>entry("sweetkiss", (from, to, move) -> (BattleEffects.Pokemon.Volatile.confusion(to) || (!BattleEffects.Pokemon.State.raised(to) && BattleEffects.Field.Terrain.mistyterrain(to))) ? 0.0 : 1.0),
        Map.<String, Evaluator>entry("teeterdance", (from, to, move) -> (BattleEffects.Pokemon.Volatile.confusion(to) || (!BattleEffects.Pokemon.State.raised(to) && BattleEffects.Field.Terrain.mistyterrain(to))) ? 0.0 : 1.0),
        Map.<String, Evaluator>entry("curse", (from, to, move) -> (TypeChart.is(from, TypeChart.GHOST) && BattleEffects.Pokemon.Volatile.cursed(to)) ? 0.0 : 1.0),
        Map.<String, Evaluator>entry("leechseed", (from, to, move) -> BattleEffects.Pokemon.Volatile.leech(to) ? 0.0 : 1.0),
        Map.<String, Evaluator>entry("ingrain", (from, to, move) -> BattleEffects.Pokemon.Volatile.ingrain(from) ? 0.0 : 1.0),
        Map.<String, Evaluator>entry("aquaring", (from, to, move) -> BattleEffects.Pokemon.Volatile.aquaring(from) ? 0.0 : 1.0),
        // Map.<String, Evaluator>entry("smackdown", (from, to, move) -> BattleEffects.Pokemon.Volatile.smackdown(to) ? 0.0 : 1.0),
        Map.<String, Evaluator>entry("telekinesis", (from, to, move) -> BattleEffects.Pokemon.State.raised(to) ? 0.0 : 1.0),
        Map.<String, Evaluator>entry("magnetrise", (from, to, move) -> BattleEffects.Pokemon.State.raised(from) ? 0.0 : 1.0),
        Map.<String, Evaluator>entry("flowershield", (from, to, move) -> from.getActor().getSide().getActivePokemon().stream().filter(p -> p.hasPokemon()).map(p -> p.getBattlePokemon()).anyMatch(p -> TypeChart.is(p, TypeChart.GRASS)) ? 1.0 : 0.0),
        Map.<String, Evaluator>entry("auroraveil", (from, to, move) -> (!BattleEffects.Side.Screen.auroraveil(from) && (BattleEffects.Field.Weather.snow(from) || BattleEffects.Field.Weather.hail(from))) ? 1.0 : 0.0),
        Map.<String, Evaluator>entry("reflect", (from, to, move) -> (BattleEffects.Side.Screen.reflect(from) || BattleEffects.Side.Screen.auroraveil(from)) ? 0.0 : 1.0),
        Map.<String, Evaluator>entry("lightscreen", (from, to, move) -> (BattleEffects.Side.Screen.lightscreen(from) || BattleEffects.Side.Screen.auroraveil(from)) ? 0.0 : 1.0),
        Map.<String, Evaluator>entry("sunnyday", (from, to, move) -> (BattleEffects.Field.Weather.harshsunlight(from) || BattleEffects.Field.Weather.extremelyharshsunlight(from) || BattleEffects.Field.Weather.heavyrain(from) || BattleEffects.Field.Weather.strongwinds(from)) ? 0.0 : 1.0),
        Map.<String, Evaluator>entry("raindance", (from, to, move) -> (BattleEffects.Field.Weather.rain(from) || BattleEffects.Field.Weather.extremelyharshsunlight(from) || BattleEffects.Field.Weather.heavyrain(from) || BattleEffects.Field.Weather.strongwinds(from)) ? 0.0 : 1.0),
        Map.<String, Evaluator>entry("sandstorm", (from, to, move) -> (BattleEffects.Field.Weather.sandstorm(from) || BattleEffects.Field.Weather.extremelyharshsunlight(from) || BattleEffects.Field.Weather.heavyrain(from) || BattleEffects.Field.Weather.strongwinds(from)) ? 0.0 : 1.0),
        Map.<String, Evaluator>entry("hail", (from, to, move) -> (BattleEffects.Field.Weather.hail(from) || BattleEffects.Field.Weather.snow(from) || BattleEffects.Field.Weather.extremelyharshsunlight(from) || BattleEffects.Field.Weather.heavyrain(from) || BattleEffects.Field.Weather.strongwinds(from)) ? 0.0 : 1.0),
        Map.<String, Evaluator>entry("electricterrain", (from, to, move) -> BattleEffects.Field.Terrain.electricterrain(from) ? 0.0 : 1.0),
        Map.<String, Evaluator>entry("grassyterrain", (from, to, move) -> BattleEffects.Field.Terrain.grassyterrain(from) ? 0.0 : 1.0),
        Map.<String, Evaluator>entry("mistyterrain", (from, to, move) -> BattleEffects.Field.Terrain.mistyterrain(from) ? 0.0 : 1.0),
        Map.<String, Evaluator>entry("psychicterrain", (from, to, move) -> BattleEffects.Field.Terrain.psychicterrain(from) ? 0.0 : 1.0),
        Map.<String, Evaluator>entry("wish", (from, to, move) -> BattleStates.get(from.actor.battle).getPokemonState(from).has(BattleEffects.Custom.WISH) ? 0.0 : 1.0),
        Map.<String, Evaluator>entry("meanlook", (from, to, move) -> BattleEffects.Pokemon.State.trapped(to) ? 0.0 : 1.0),
        Map.<String, Evaluator>entry("spiderweb", (from, to, move) -> BattleEffects.Pokemon.State.trapped(to) ? 0.0 : 1.0),
        Map.<String, Evaluator>entry("block", (from, to, move) -> BattleEffects.Pokemon.State.trapped(to) ? 0.0 : 1.0),
        Map.<String, Evaluator>entry("fakeout", (from, to, move) -> BattleStates.get(from.actor.battle).getPokemonState(from).age(BattleEffects.Custom.TURN) > 1 ? 0.0 : 1.75),
        Map.<String, Evaluator>entry("tailwind", (from, to, move) -> BattleEffects.Side.Tailwind.tailwind(from) ? 0.0 : 1.0),
        Map.<String, Evaluator>entry("gravity", (from, to, move) -> BattleEffects.Field.Gravity.gravity(from) ? 0.0 : 1.0),
        Map.<String, Evaluator>entry("trickroom", (from, to, move) -> BattleEffects.Field.Room.trickroom(from) ? 0.0 : 1.0),
        Map.<String, Evaluator>entry("spikes", (from, to, move) -> (3 - BattleEffects.Side.Hazard.spikes(to))/3.0),
        Map.<String, Evaluator>entry("stealthrock", (from, to, move) -> BattleEffects.Side.Hazard.stealthrock(to) > 0 ? 0.0 : 1.0),
        Map.<String, Evaluator>entry("toxicspikes", (from, to, move) -> (2 - BattleEffects.Side.Hazard.toxicspikes(to))/2.0),
        Map.<String, Evaluator>entry("stickyweb", (from, to, move) -> BattleEffects.Side.Hazard.stickyweb(to) > 0 ? 0.0 : 1.0),
        // Map.<String, Evaluator>entry("steelsurge", (from, to, move) -> BattleEffects.Side.Hazard.sharpsteel(to) > 0 ? 0.0 : 1.0),
        Map.<String, Evaluator>entry("protect", (from, to, move) -> BattleStates.get(from.actor.battle).getPokemonState(from).has(BattleEffects.Custom.PROTECT) ? 0.15 : 1.0),
        Map.<String, Evaluator>entry("detect", (from, to, move) -> BattleStates.get(from.actor.battle).getPokemonState(from).has(BattleEffects.Custom.PROTECT) ? 0.15 : 1.0),
        Map.<String, Evaluator>entry("endure", (from, to, move) -> BattleStates.get(from.actor.battle).getPokemonState(from).has(BattleEffects.Custom.PROTECT) ? 0.15 : 1.0),
        Map.<String, Evaluator>entry("wideguard", (from, to, move) -> BattleStates.get(from.actor.battle).getPokemonState(from).has(BattleEffects.Custom.PROTECT) ? 0.15 : 1.0),
        Map.<String, Evaluator>entry("quickguard", (from, to, move) -> BattleStates.get(from.actor.battle).getPokemonState(from).has(BattleEffects.Custom.PROTECT) ? 0.15 : 1.0),
        Map.<String, Evaluator>entry("spikyshield", (from, to, move) -> BattleStates.get(from.actor.battle).getPokemonState(from).has(BattleEffects.Custom.PROTECT) ? 0.15 : 1.0),
        Map.<String, Evaluator>entry("kingsshield", (from, to, move) -> BattleStates.get(from.actor.battle).getPokemonState(from).has(BattleEffects.Custom.PROTECT) ? 0.15 : 1.0),
        Map.<String, Evaluator>entry("banefulbunker", (from, to, move) -> BattleStates.get(from.actor.battle).getPokemonState(from).has(BattleEffects.Custom.PROTECT) ? 0.15 : 1.0),
        Map.<String, Evaluator>entry("taunt", (from, to, move) -> BattleEffects.Pokemon.Volatile.taunt(to) ? 0 : 1.0),
        //PARALYSIS https://bulbapedia.bulbagarden.net/wiki/Paralysis_(status_condition)#Prevention TODO: leafguard + harshsunlight, etc.
        Map.<String, Evaluator>entry("glare", (from, to, move) -> (BattleEffects.Pokemon.Status.any(to) || TypeChart.is(to, TypeChart.ELECTRIC) || ability(to, "limber", "comatose", "purifyingsalt")) ? 0 : 1.0),
        Map.<String, Evaluator>entry("stunspore", (from, to, move) -> (BattleEffects.Pokemon.Status.any(to) || TypeChart.is(to, TypeChart.ELECTRIC | TypeChart.GRASS) || ability(to, "limber", "comatose", "purifyingsalt")) ? 0 : 1.0),
        Map.<String, Evaluator>entry("thunderwave", (from, to, move) -> (BattleEffects.Pokemon.Status.any(to) || TypeChart.is(to, TypeChart.ELECTRIC | TypeChart.GROUND) || ability(to, "limber", "comatose", "purifyingsalt")) ? 0 : 1.0),
        // POISON https://bulbapedia.bulbagarden.net/wiki/Poison_(status_condition)#Prevention TODO: mistyterrain + grounded, etc.
        Map.<String, Evaluator>entry("poisongas", (from, to, move) -> (BattleEffects.Pokemon.Status.any(to) || (TypeChart.is(to, TypeChart.POISON | TypeChart.STEEL) && !ability(from, "corrosion")) || ability(to, "immunity", "comatose", "purifyingsalt", "pastelveil")) ? 0 : 1.0),
        Map.<String, Evaluator>entry("poisonpowder", (from, to, move) -> (BattleEffects.Pokemon.Status.any(to) || (TypeChart.is(to, TypeChart.POISON | TypeChart.STEEL | TypeChart.GRASS) && !ability(from, "corrosion")) || ability(to, "immunity", "comatose", "purifyingsalt", "pastelveil")) ? 0 : 1.0),
        Map.<String, Evaluator>entry("toxicthread", (from, to, move) -> (BattleEffects.Pokemon.Status.any(to) || (TypeChart.is(to, TypeChart.POISON | TypeChart.STEEL) && !ability(from, "corrosion")) || ability(to, "immunity", "comatose", "purifyingsalt", "pastelveil")) ? 0.25 : 1.0),
        Map.<String, Evaluator>entry("toxic", (from, to, move) -> (BattleEffects.Pokemon.Status.any(to) || (TypeChart.is(to, TypeChart.POISON | TypeChart.STEEL) && !ability(from, "corrosion")) || ability(to, "immunity", "comatose", "purifyingsalt", "pastelveil")) ? 0 : 1.0),
        // BURN https://bulbapedia.bulbagarden.net/wiki/Burn_(status_condition)#Prevention TODO: leafguard + harshsunlight, etc.
        Map.<String, Evaluator>entry("willowisp", (from, to, move) -> (BattleEffects.Pokemon.Status.any(to) || TypeChart.is(to, TypeChart.FIRE) || ability(to, "waterveil", "waterbubble", "comatose", "thermalexchange", "purifyingsalt")) ? 0 : 1.0),
        // SLEEP https://bulbapedia.bulbagarden.net/wiki/Sleep_(status_condition)#Prevention TODO: electricterrain + grounded, etc.
        Map.<String, Evaluator>entry("darkvoid", (from, to, move) -> (BattleEffects.Pokemon.Status.any(to) || ability(to, "insomnia", "vitalspirit", "purifyingsalt", "comatose")) ? 0.5 : 1.0),
        Map.<String, Evaluator>entry("grasswhistle", (from, to, move) -> (BattleEffects.Pokemon.Status.any(to) || ability(to, "insomnia", "vitalspirit", "purifyingsalt", "comatose", "soundproof")) ? 0 : 1.0),
        Map.<String, Evaluator>entry("hypnosis", (from, to, move) -> (BattleEffects.Pokemon.Status.any(to) || ability(to, "insomnia", "vitalspirit", "purifyingsalt", "comatose")) ? 0 : 1.0),
        Map.<String, Evaluator>entry("lovelykiss", (from, to, move) -> (BattleEffects.Pokemon.Status.any(to) || ability(to, "insomnia", "vitalspirit", "purifyingsalt", "comatose")) ? 0 : 1.0),
        Map.<String, Evaluator>entry("sing", (from, to, move) -> (BattleEffects.Pokemon.Status.any(to) || ability(to, "insomnia", "vitalspirit", "purifyingsalt", "comatose", "soundproof")) ? 0 : 1.0),
        Map.<String, Evaluator>entry("sleeppowder", (from, to, move) -> (BattleEffects.Pokemon.Status.any(to) || TypeChart.is(to, TypeChart.GRASS) || ability(to, "insomnia", "vitalspirit", "purifyingsalt", "comatose", "overcoat")) ? 0 : 1.0),
        Map.<String, Evaluator>entry("spore", (from, to, move) -> (BattleEffects.Pokemon.Status.any(to) || TypeChart.is(to, TypeChart.GRASS) || ability(to, "insomnia", "vitalspirit", "purifyingsalt", "comatose", "overcoat")) ? 0 : 1.0),
        Map.<String, Evaluator>entry("yawn", (from, to, move) -> (BattleEffects.Pokemon.Volatile.yawn(to) || BattleEffects.Pokemon.Status.any(to) || ability(to, "insomnia", "vitalspirit", "purifyingsalt", "comatose")) ? 0.0 : 1.0),
        Map.<String, Evaluator>entry("sleeptalk", (from, to, move) -> (BattleEffects.Pokemon.Status.slp(from) || ability(from, "comatose")) ? 1.0 : 0.0),
        Map.<String, Evaluator>entry("snore", (from, to, move) -> (BattleEffects.Pokemon.Status.slp(from) || ability(from, "comatose")) ? 1.0 : 0.0),
        // SACRIFICE https://bulbapedia.bulbagarden.net/wiki/Category:Moves_that_cause_the_user_to_faint
        Map.<String, Evaluator>entry("explosion", (from, to, move) -> ability(to, "damp") ? 0.0 : (1.0 - 0.5 * (from.getHealth() / (double)from.getMaxHealth()))),
        Map.<String, Evaluator>entry("mistyexplosion", (from, to, move) -> ability(to, "damp") ? 0.0 : (1.0 - 0.5 * (from.getHealth() / (double)from.getMaxHealth()))),
        Map.<String, Evaluator>entry("selfdestruct", (from, to, move) -> ability(to, "damp") ? 0.0 : (1.0 - 0.5 * (from.getHealth() / (double)from.getMaxHealth()))),
        Map.<String, Evaluator>entry("lunardance", (from, to, move) -> 1.0 - 0.5 * (from.getHealth() / (double)from.getMaxHealth())),
        Map.<String, Evaluator>entry("finalgambit", (from, to, move) -> 1.0 - 0.5 * (from.getHealth() / (double)from.getMaxHealth())),
        Map.<String, Evaluator>entry("memento", (from, to, move) -> 1.0 - 0.5 * (from.getHealth() / (double)from.getMaxHealth())),
        Map.<String, Evaluator>entry("healingwish", (from, to, move) -> 1.0 - 0.5 * (from.getHealth() / (double)from.getMaxHealth()))
    );

    // custom move event handlers
    private static final Map<String, Handler> MOVE_HANDLERS = Map.<String, Handler>ofEntries(
        Map.<String, Handler>entry("wish", (f, t) -> BattleStates.get(f.actor.battle).getPokemonState(f).add(BattleEffects.Custom.WISH)),
        Map.<String, Handler>entry("meanlook", (f, t) -> BattleStates.get(f.actor.battle).getPokemonState(f).add(BattleEffects.Custom.MEANLOOK)),
        Map.<String, Handler>entry("spiderweb", (f, t) -> BattleStates.get(f.actor.battle).getPokemonState(f).add(BattleEffects.Custom.SPIDERWEB)),
        Map.<String, Handler>entry("block", (f, t) -> BattleStates.get(f.actor.battle).getPokemonState(f).add(BattleEffects.Custom.BLOCK)),
        Map.<String, Handler>entry("protect", (f, t) -> BattleStates.get(f.actor.battle).getPokemonState(f).add(BattleEffects.Custom.PROTECT)),
        Map.<String, Handler>entry("detect", (f, t) -> BattleStates.get(f.actor.battle).getPokemonState(f).add(BattleEffects.Custom.PROTECT)),
        Map.<String, Handler>entry("endure", (f, t) -> BattleStates.get(f.actor.battle).getPokemonState(f).add(BattleEffects.Custom.PROTECT)),
        Map.<String, Handler>entry("wideguard", (f, t) -> BattleStates.get(f.actor.battle).getPokemonState(f).add(BattleEffects.Custom.PROTECT)),
        Map.<String, Handler>entry("quickguard", (f, t) -> BattleStates.get(f.actor.battle).getPokemonState(f).add(BattleEffects.Custom.PROTECT)),
        Map.<String, Handler>entry("spikyshield", (f, t) -> BattleStates.get(f.actor.battle).getPokemonState(f).add(BattleEffects.Custom.PROTECT)),
        Map.<String, Handler>entry("kingsshield", (f, t) -> BattleStates.get(f.actor.battle).getPokemonState(f).add(BattleEffects.Custom.PROTECT)),
        Map.<String, Handler>entry("banefulbunker", (f, t) -> BattleStates.get(f.actor.battle).getPokemonState(f).add(BattleEffects.Custom.PROTECT))
    );

    // all moves according to https://pokemondb.net/move/all (05/2025)
    private static final Map<String, MoveType> MOVE_TYPES = Map.<String, MoveType>ofEntries(
        Map.<String, MoveType>entry("10000000voltthunderbolt", DAMAGE),
        Map.<String, MoveType>entry("absorb", DAMAGE),
        Map.<String, MoveType>entry("accelerock", DAMAGE),
        Map.<String, MoveType>entry("acid", DAMAGE),
        Map.<String, MoveType>entry("acidarmor", BUFF),
        Map.<String, MoveType>entry("aciddownpour", DAMAGE),
        Map.<String, MoveType>entry("acidspray", DAMAGE),
        Map.<String, MoveType>entry("acrobatics", DAMAGE),
        Map.<String, MoveType>entry("acupressure", BUFF),
        Map.<String, MoveType>entry("aerialace", DAMAGE),
        Map.<String, MoveType>entry("aeroblast", DAMAGE),
        Map.<String, MoveType>entry("afteryou", STATUS),
        Map.<String, MoveType>entry("agility", BUFF),
        Map.<String, MoveType>entry("aircutter", DAMAGE),
        Map.<String, MoveType>entry("airslash", DAMAGE),
        Map.<String, MoveType>entry("alloutpummeling", DAMAGE),
        Map.<String, MoveType>entry("alluringvoice", DAMAGE),
        Map.<String, MoveType>entry("allyswitch", STATUS),
        Map.<String, MoveType>entry("amnesia", BUFF),
        Map.<String, MoveType>entry("anchorshot", DAMAGE),
        Map.<String, MoveType>entry("ancientpower", DAMAGE),
        Map.<String, MoveType>entry("appleacid", DAMAGE),
        Map.<String, MoveType>entry("aquacutter", DAMAGE),
        Map.<String, MoveType>entry("aquajet", DAMAGE),
        Map.<String, MoveType>entry("aquaring", HEAL),
        Map.<String, MoveType>entry("aquastep", DAMAGE),
        Map.<String, MoveType>entry("aquatail", DAMAGE),
        Map.<String, MoveType>entry("armthrust", DAMAGE),
        Map.<String, MoveType>entry("armorcannon", DAMAGE),
        Map.<String, MoveType>entry("aromatherapy", CURE),
        Map.<String, MoveType>entry("aromaticmist", BUFF),
        Map.<String, MoveType>entry("assist", STATUS),
        Map.<String, MoveType>entry("assurance", DAMAGE),
        Map.<String, MoveType>entry("astonish", DAMAGE),
        Map.<String, MoveType>entry("astralbarrage", DAMAGE),
        Map.<String, MoveType>entry("attackorder", DAMAGE),
        Map.<String, MoveType>entry("attract", STATUS),
        Map.<String, MoveType>entry("aurasphere", DAMAGE),
        Map.<String, MoveType>entry("aurawheel", DAMAGE),
        Map.<String, MoveType>entry("aurorabeam", DAMAGE),
        Map.<String, MoveType>entry("auroraveil", BUFF),
        Map.<String, MoveType>entry("autotomize", BUFF),
        Map.<String, MoveType>entry("avalanche", DAMAGE),
        Map.<String, MoveType>entry("axekick", DAMAGE),
        Map.<String, MoveType>entry("babydolleyes", MALUS),
        Map.<String, MoveType>entry("baddybad", DAMAGE),
        Map.<String, MoveType>entry("banefulbunker", STATUS),
        Map.<String, MoveType>entry("barbbarrage", DAMAGE),
        Map.<String, MoveType>entry("barrage", DAMAGE),
        Map.<String, MoveType>entry("barrier", BUFF),
        Map.<String, MoveType>entry("batonpass", STATUS),
        Map.<String, MoveType>entry("beakblast", DAMAGE),
        Map.<String, MoveType>entry("beatup", DAMAGE),
        Map.<String, MoveType>entry("behemothbash", DAMAGE),
        Map.<String, MoveType>entry("behemothblade", DAMAGE),
        Map.<String, MoveType>entry("belch", DAMAGE),
        Map.<String, MoveType>entry("bellydrum", BUFF),
        Map.<String, MoveType>entry("bestow", STATUS),
        Map.<String, MoveType>entry("bide", DAMAGE),
        Map.<String, MoveType>entry("bind", DAMAGE),
        Map.<String, MoveType>entry("bite", DAMAGE),
        Map.<String, MoveType>entry("bitterblade", DAMAGE),
        Map.<String, MoveType>entry("bittermalice", DAMAGE),
        Map.<String, MoveType>entry("blackholeeclipse", DAMAGE),
        Map.<String, MoveType>entry("blastburn", DAMAGE),
        Map.<String, MoveType>entry("blazekick", DAMAGE),
        Map.<String, MoveType>entry("blazingtorque", DAMAGE),
        Map.<String, MoveType>entry("bleakwindstorm", DAMAGE),
        Map.<String, MoveType>entry("blizzard", DAMAGE),
        Map.<String, MoveType>entry("block", STATUS),
        Map.<String, MoveType>entry("bloodmoon", DAMAGE),
        Map.<String, MoveType>entry("bloomdoom", DAMAGE),
        Map.<String, MoveType>entry("blueflare", DAMAGE),
        Map.<String, MoveType>entry("bodypress", DAMAGE),
        Map.<String, MoveType>entry("bodyslam", DAMAGE),
        Map.<String, MoveType>entry("boltbeak", DAMAGE),
        Map.<String, MoveType>entry("boltstrike", DAMAGE),
        Map.<String, MoveType>entry("boneclub", DAMAGE),
        Map.<String, MoveType>entry("bonerush", DAMAGE),
        Map.<String, MoveType>entry("bonemerang", DAMAGE),
        Map.<String, MoveType>entry("boomburst", DAMAGE),
        Map.<String, MoveType>entry("bounce", DAMAGE),
        Map.<String, MoveType>entry("bouncybubble", DAMAGE),
        Map.<String, MoveType>entry("branchpoke", DAMAGE),
        Map.<String, MoveType>entry("bravebird", DAMAGE),
        Map.<String, MoveType>entry("breakingswipe", DAMAGE),
        Map.<String, MoveType>entry("breakneckblitz", DAMAGE),
        Map.<String, MoveType>entry("brickbreak", DAMAGE),
        Map.<String, MoveType>entry("brine", DAMAGE),
        Map.<String, MoveType>entry("brutalswing", DAMAGE),
        Map.<String, MoveType>entry("bubble", DAMAGE),
        Map.<String, MoveType>entry("bubblebeam", DAMAGE),
        Map.<String, MoveType>entry("bugbite", DAMAGE),
        Map.<String, MoveType>entry("bugbuzz", DAMAGE),
        Map.<String, MoveType>entry("bulkup", BUFF),
        Map.<String, MoveType>entry("bulldoze", DAMAGE),
        Map.<String, MoveType>entry("bulletpunch", DAMAGE),
        Map.<String, MoveType>entry("bulletseed", DAMAGE),
        Map.<String, MoveType>entry("burnup", DAMAGE),
        Map.<String, MoveType>entry("burningbulwark", BUFF),
        Map.<String, MoveType>entry("burningjealousy", DAMAGE),
        Map.<String, MoveType>entry("buzzybuzz", DAMAGE),
        Map.<String, MoveType>entry("calmmind", BUFF),
        Map.<String, MoveType>entry("camouflage", STATUS),
        Map.<String, MoveType>entry("captivate", MALUS),
        Map.<String, MoveType>entry("catastropika", DAMAGE),
        Map.<String, MoveType>entry("ceaselessedge", DAMAGE),
        Map.<String, MoveType>entry("celebrate", STATUS),
        Map.<String, MoveType>entry("charge", BUFF),
        Map.<String, MoveType>entry("chargebeam", DAMAGE),
        Map.<String, MoveType>entry("charm", MALUS),
        Map.<String, MoveType>entry("chatter", DAMAGE),
        Map.<String, MoveType>entry("chillingwater", DAMAGE),
        Map.<String, MoveType>entry("chillyreception", STATUS),
        Map.<String, MoveType>entry("chipaway", DAMAGE),
        Map.<String, MoveType>entry("chloroblast", DAMAGE),
        Map.<String, MoveType>entry("circlethrow", DAMAGE),
        Map.<String, MoveType>entry("clamp", DAMAGE),
        Map.<String, MoveType>entry("clangingscales", DAMAGE),
        Map.<String, MoveType>entry("clangoroussoul", BUFF),
        Map.<String, MoveType>entry("clangoroussoulblaze", DAMAGE),
        Map.<String, MoveType>entry("clearsmog", DAMAGE),
        Map.<String, MoveType>entry("closecombat", DAMAGE),
        Map.<String, MoveType>entry("coaching", BUFF),
        Map.<String, MoveType>entry("coil", BUFF),
        Map.<String, MoveType>entry("collisioncourse", DAMAGE),
        Map.<String, MoveType>entry("combattorque", DAMAGE),
        Map.<String, MoveType>entry("cometpunch", DAMAGE),
        Map.<String, MoveType>entry("comeuppance", DAMAGE),
        Map.<String, MoveType>entry("confide", STATUS),
        Map.<String, MoveType>entry("confuseray", STATUS),
        Map.<String, MoveType>entry("confusion", DAMAGE),
        Map.<String, MoveType>entry("constrict", DAMAGE),
        Map.<String, MoveType>entry("continentalcrush", DAMAGE),
        Map.<String, MoveType>entry("conversion", STATUS),
        Map.<String, MoveType>entry("conversion2", STATUS),
        Map.<String, MoveType>entry("copycat", STATUS),
        Map.<String, MoveType>entry("coreenforcer", DAMAGE),
        Map.<String, MoveType>entry("corkscrewcrash", DAMAGE),
        Map.<String, MoveType>entry("corrosivegas", MALUS),
        Map.<String, MoveType>entry("cosmicpower", BUFF),
        Map.<String, MoveType>entry("cottonguard", BUFF),
        Map.<String, MoveType>entry("cottonspore", MALUS),
        Map.<String, MoveType>entry("counter", DAMAGE),
        Map.<String, MoveType>entry("courtchange", STATUS),
        Map.<String, MoveType>entry("covet", DAMAGE),
        Map.<String, MoveType>entry("crabhammer", DAMAGE),
        Map.<String, MoveType>entry("craftyshield", STATUS),
        Map.<String, MoveType>entry("crosschop", DAMAGE),
        Map.<String, MoveType>entry("crosspoison", DAMAGE),
        Map.<String, MoveType>entry("crunch", DAMAGE),
        Map.<String, MoveType>entry("crushclaw", DAMAGE),
        Map.<String, MoveType>entry("crushgrip", DAMAGE),
        Map.<String, MoveType>entry("curse", STATUS),
        Map.<String, MoveType>entry("cut", DAMAGE),
        Map.<String, MoveType>entry("darkpulse", DAMAGE),
        Map.<String, MoveType>entry("darkvoid", STATUS),
        Map.<String, MoveType>entry("darkestlariat", DAMAGE),
        Map.<String, MoveType>entry("dazzlinggleam", DAMAGE),
        Map.<String, MoveType>entry("decorate", BUFF),
        Map.<String, MoveType>entry("defendorder", BUFF),
        Map.<String, MoveType>entry("defensecurl", BUFF),
        Map.<String, MoveType>entry("defog", STATUS),
        Map.<String, MoveType>entry("destinybond", STATUS),
        Map.<String, MoveType>entry("detect", STATUS),
        Map.<String, MoveType>entry("devastatingdrake", DAMAGE),
        Map.<String, MoveType>entry("diamondstorm", DAMAGE),
        Map.<String, MoveType>entry("dig", DAMAGE),
        Map.<String, MoveType>entry("direclaw", DAMAGE),
        Map.<String, MoveType>entry("disable", STATUS),
        Map.<String, MoveType>entry("disarmingvoice", DAMAGE),
        Map.<String, MoveType>entry("discharge", DAMAGE),
        Map.<String, MoveType>entry("dive", DAMAGE),
        Map.<String, MoveType>entry("dizzypunch", DAMAGE),
        Map.<String, MoveType>entry("doodle", STATUS),
        Map.<String, MoveType>entry("doomdesire", DAMAGE),
        Map.<String, MoveType>entry("doublehit", DAMAGE),
        Map.<String, MoveType>entry("doubleironbash", DAMAGE),
        Map.<String, MoveType>entry("doublekick", DAMAGE),
        Map.<String, MoveType>entry("doubleshock", DAMAGE),
        Map.<String, MoveType>entry("doubleslap", DAMAGE),
        Map.<String, MoveType>entry("doubleteam", STATUS),
        Map.<String, MoveType>entry("doubleedge", DAMAGE),
        Map.<String, MoveType>entry("dracometeor", DAMAGE),
        Map.<String, MoveType>entry("dragonascent", DAMAGE),
        Map.<String, MoveType>entry("dragonbreath", DAMAGE),
        Map.<String, MoveType>entry("dragoncheer", BUFF),
        Map.<String, MoveType>entry("dragonclaw", DAMAGE),
        Map.<String, MoveType>entry("dragondance", BUFF),
        Map.<String, MoveType>entry("dragondarts", DAMAGE),
        Map.<String, MoveType>entry("dragonenergy", DAMAGE),
        Map.<String, MoveType>entry("dragonhammer", DAMAGE),
        Map.<String, MoveType>entry("dragonpulse", DAMAGE),
        Map.<String, MoveType>entry("dragonrage", DAMAGE),
        Map.<String, MoveType>entry("dragonrush", DAMAGE),
        Map.<String, MoveType>entry("dragontail", DAMAGE),
        Map.<String, MoveType>entry("drainpunch", DAMAGE),
        Map.<String, MoveType>entry("drainingkiss", DAMAGE),
        Map.<String, MoveType>entry("dreameater", DAMAGE),
        Map.<String, MoveType>entry("drillpeck", DAMAGE),
        Map.<String, MoveType>entry("drillrun", DAMAGE),
        Map.<String, MoveType>entry("drumbeating", DAMAGE),
        Map.<String, MoveType>entry("dualchop", DAMAGE),
        Map.<String, MoveType>entry("dualwingbeat", DAMAGE),
        Map.<String, MoveType>entry("dynamaxcannon", DAMAGE),
        Map.<String, MoveType>entry("dynamicpunch", DAMAGE),
        Map.<String, MoveType>entry("earthpower", DAMAGE),
        Map.<String, MoveType>entry("earthquake", DAMAGE),
        Map.<String, MoveType>entry("echoedvoice", DAMAGE),
        Map.<String, MoveType>entry("eerieimpulse", MALUS),
        Map.<String, MoveType>entry("eeriespell", DAMAGE),
        Map.<String, MoveType>entry("eggbomb", DAMAGE),
        Map.<String, MoveType>entry("electricterrain", STATUS),
        Map.<String, MoveType>entry("electrify", STATUS),
        Map.<String, MoveType>entry("electroball", DAMAGE),
        Map.<String, MoveType>entry("electrodrift", DAMAGE),
        Map.<String, MoveType>entry("electroshot", DAMAGE),
        Map.<String, MoveType>entry("electroweb", DAMAGE),
        Map.<String, MoveType>entry("embargo", STATUS),
        Map.<String, MoveType>entry("ember", DAMAGE),
        Map.<String, MoveType>entry("encore", STATUS),
        Map.<String, MoveType>entry("endeavor", DAMAGE),
        Map.<String, MoveType>entry("endure", STATUS),
        Map.<String, MoveType>entry("energyball", DAMAGE),
        Map.<String, MoveType>entry("entrainment", STATUS),
        Map.<String, MoveType>entry("eruption", DAMAGE),
        Map.<String, MoveType>entry("esperwing", DAMAGE),
        Map.<String, MoveType>entry("eternabeam", DAMAGE),
        Map.<String, MoveType>entry("expandingforce", DAMAGE),
        Map.<String, MoveType>entry("explosion", DAMAGE),
        Map.<String, MoveType>entry("extrasensory", DAMAGE),
        Map.<String, MoveType>entry("extremeevoboost", BUFF),
        Map.<String, MoveType>entry("extremespeed", DAMAGE),
        Map.<String, MoveType>entry("facade", DAMAGE),
        Map.<String, MoveType>entry("fairylock", STATUS),
        Map.<String, MoveType>entry("fairywind", DAMAGE),
        Map.<String, MoveType>entry("fakeout", DAMAGE),
        Map.<String, MoveType>entry("faketears", MALUS),
        Map.<String, MoveType>entry("falsesurrender", DAMAGE),
        Map.<String, MoveType>entry("falseswipe", DAMAGE),
        Map.<String, MoveType>entry("featherdance", MALUS),
        Map.<String, MoveType>entry("feint", DAMAGE),
        Map.<String, MoveType>entry("feintattack", DAMAGE),
        Map.<String, MoveType>entry("fellstinger", DAMAGE),
        Map.<String, MoveType>entry("ficklebeam", DAMAGE),
        Map.<String, MoveType>entry("fierydance", DAMAGE),
        Map.<String, MoveType>entry("fierywrath", DAMAGE),
        Map.<String, MoveType>entry("filletaway", STATUS),
        Map.<String, MoveType>entry("finalgambit", DAMAGE),
        Map.<String, MoveType>entry("fireblast", DAMAGE),
        Map.<String, MoveType>entry("firefang", DAMAGE),
        Map.<String, MoveType>entry("firelash", DAMAGE),
        Map.<String, MoveType>entry("firepledge", DAMAGE),
        Map.<String, MoveType>entry("firepunch", DAMAGE),
        Map.<String, MoveType>entry("firespin", DAMAGE),
        Map.<String, MoveType>entry("firstimpression", DAMAGE),
        Map.<String, MoveType>entry("fishiousrend", DAMAGE),
        Map.<String, MoveType>entry("fissure", DAMAGE),
        Map.<String, MoveType>entry("flail", DAMAGE),
        Map.<String, MoveType>entry("flameburst", DAMAGE),
        Map.<String, MoveType>entry("flamecharge", DAMAGE),
        Map.<String, MoveType>entry("flamewheel", DAMAGE),
        Map.<String, MoveType>entry("flamethrower", DAMAGE),
        Map.<String, MoveType>entry("flareblitz", DAMAGE),
        Map.<String, MoveType>entry("flash", STATUS),
        Map.<String, MoveType>entry("flashcannon", DAMAGE),
        Map.<String, MoveType>entry("flatter", MALUS),
        Map.<String, MoveType>entry("fleurcannon", DAMAGE),
        Map.<String, MoveType>entry("fling", DAMAGE),
        Map.<String, MoveType>entry("flipturn", DAMAGE),
        Map.<String, MoveType>entry("floatyfall", DAMAGE),
        Map.<String, MoveType>entry("floralhealing", HEAL),
        Map.<String, MoveType>entry("flowershield", BUFF),
        Map.<String, MoveType>entry("flowertrick", DAMAGE),
        Map.<String, MoveType>entry("fly", DAMAGE),
        Map.<String, MoveType>entry("flyingpress", DAMAGE),
        Map.<String, MoveType>entry("focusblast", DAMAGE),
        Map.<String, MoveType>entry("focusenergy", BUFF),
        Map.<String, MoveType>entry("focuspunch", DAMAGE),
        Map.<String, MoveType>entry("followme", STATUS),
        Map.<String, MoveType>entry("forcepalm", DAMAGE),
        Map.<String, MoveType>entry("foresight", STATUS),
        Map.<String, MoveType>entry("forestscurse", STATUS),
        Map.<String, MoveType>entry("foulplay", DAMAGE),
        Map.<String, MoveType>entry("freezeshock", DAMAGE),
        Map.<String, MoveType>entry("freezedry", DAMAGE),
        Map.<String, MoveType>entry("freezingglare", DAMAGE),
        Map.<String, MoveType>entry("freezyfrost", DAMAGE),
        Map.<String, MoveType>entry("frenzyplant", DAMAGE),
        Map.<String, MoveType>entry("frostbreath", DAMAGE),
        Map.<String, MoveType>entry("frustration", DAMAGE),
        Map.<String, MoveType>entry("furyattack", DAMAGE),
        Map.<String, MoveType>entry("furycutter", DAMAGE),
        Map.<String, MoveType>entry("furyswipes", DAMAGE),
        Map.<String, MoveType>entry("fusionbolt", DAMAGE),
        Map.<String, MoveType>entry("fusionflare", DAMAGE),
        Map.<String, MoveType>entry("futuresight", DAMAGE),
        Map.<String, MoveType>entry("gmaxbefuddle", DAMAGE),
        Map.<String, MoveType>entry("gmaxcannonade", DAMAGE),
        Map.<String, MoveType>entry("gmaxcentiferno", DAMAGE),
        Map.<String, MoveType>entry("gmaxchistrike", DAMAGE),
        Map.<String, MoveType>entry("gmaxcuddle", DAMAGE),
        Map.<String, MoveType>entry("gmaxdepletion", DAMAGE),
        Map.<String, MoveType>entry("gmaxdrumsolo", DAMAGE),
        Map.<String, MoveType>entry("gmaxfinale", DAMAGE),
        Map.<String, MoveType>entry("gmaxfireball", DAMAGE),
        Map.<String, MoveType>entry("gmaxfoamburst", DAMAGE),
        Map.<String, MoveType>entry("gmaxgoldrush", DAMAGE),
        Map.<String, MoveType>entry("gmaxgravitas", DAMAGE),
        Map.<String, MoveType>entry("gmaxhydrosnipe", DAMAGE),
        Map.<String, MoveType>entry("gmaxmalodor", DAMAGE),
        Map.<String, MoveType>entry("gmaxmeltdown", DAMAGE),
        Map.<String, MoveType>entry("gmaxoneblow", DAMAGE),
        Map.<String, MoveType>entry("gmaxrapidflow", DAMAGE),
        Map.<String, MoveType>entry("gmaxreplenish", DAMAGE),
        Map.<String, MoveType>entry("gmaxresonance", DAMAGE),
        Map.<String, MoveType>entry("gmaxsandblast", DAMAGE),
        Map.<String, MoveType>entry("gmaxsmite", DAMAGE),
        Map.<String, MoveType>entry("gmaxsnooze", DAMAGE),
        Map.<String, MoveType>entry("gmaxsteelsurge", DAMAGE),
        Map.<String, MoveType>entry("gmaxstonesurge", DAMAGE),
        Map.<String, MoveType>entry("gmaxstunshock", DAMAGE),
        Map.<String, MoveType>entry("gmaxsweetness", DAMAGE),
        Map.<String, MoveType>entry("gmaxtartness", DAMAGE),
        Map.<String, MoveType>entry("gmaxterror", DAMAGE),
        Map.<String, MoveType>entry("gmaxvinelash", DAMAGE),
        Map.<String, MoveType>entry("gmaxvolcalith", DAMAGE),
        Map.<String, MoveType>entry("gmaxvoltcrash", DAMAGE),
        Map.<String, MoveType>entry("gmaxwildfire", DAMAGE),
        Map.<String, MoveType>entry("gmaxwindrage", DAMAGE),
        Map.<String, MoveType>entry("gastroacid", MALUS),
        Map.<String, MoveType>entry("geargrind", DAMAGE),
        Map.<String, MoveType>entry("gearup", BUFF),
        Map.<String, MoveType>entry("genesissupernova", DAMAGE),
        Map.<String, MoveType>entry("geomancy", BUFF),
        Map.<String, MoveType>entry("gigadrain", DAMAGE),
        Map.<String, MoveType>entry("gigaimpact", DAMAGE),
        Map.<String, MoveType>entry("gigatonhammer", DAMAGE),
        Map.<String, MoveType>entry("gigavolthavoc", DAMAGE),
        Map.<String, MoveType>entry("glaciallance", DAMAGE),
        Map.<String, MoveType>entry("glaciate", DAMAGE),
        Map.<String, MoveType>entry("glaiverush", DAMAGE),
        Map.<String, MoveType>entry("glare", STATUS),
        Map.<String, MoveType>entry("glitzyglow", DAMAGE),
        Map.<String, MoveType>entry("grassknot", DAMAGE),
        Map.<String, MoveType>entry("grasspledge", DAMAGE),
        Map.<String, MoveType>entry("grasswhistle", STATUS),
        Map.<String, MoveType>entry("grassyglide", DAMAGE),
        Map.<String, MoveType>entry("grassyterrain", STATUS),
        Map.<String, MoveType>entry("gravapple", DAMAGE),
        Map.<String, MoveType>entry("gravity", STATUS),
        Map.<String, MoveType>entry("growl", MALUS),
        Map.<String, MoveType>entry("growth", BUFF),
        Map.<String, MoveType>entry("grudge", STATUS),
        Map.<String, MoveType>entry("guardsplit", STATUS),
        Map.<String, MoveType>entry("guardswap", STATUS),
        Map.<String, MoveType>entry("guardianofalola", DAMAGE),
        Map.<String, MoveType>entry("guillotine", DAMAGE),
        Map.<String, MoveType>entry("gunkshot", DAMAGE),
        Map.<String, MoveType>entry("gust", DAMAGE),
        Map.<String, MoveType>entry("gyroball", DAMAGE),
        Map.<String, MoveType>entry("hail", STATUS),
        Map.<String, MoveType>entry("hammerarm", DAMAGE),
        Map.<String, MoveType>entry("happyhour", STATUS),
        Map.<String, MoveType>entry("hardpress", DAMAGE),
        Map.<String, MoveType>entry("harden", BUFF),
        Map.<String, MoveType>entry("haze", STATUS),
        Map.<String, MoveType>entry("headcharge", DAMAGE),
        Map.<String, MoveType>entry("headsmash", DAMAGE),
        Map.<String, MoveType>entry("headbutt", DAMAGE),
        Map.<String, MoveType>entry("headlongrush", DAMAGE),
        Map.<String, MoveType>entry("healbell", CURE),
        Map.<String, MoveType>entry("healblock", STATUS),
        Map.<String, MoveType>entry("healorder", HEAL),
        Map.<String, MoveType>entry("healpulse", HEAL),
        Map.<String, MoveType>entry("healingwish", HEAL),
        Map.<String, MoveType>entry("heartstamp", DAMAGE),
        Map.<String, MoveType>entry("heartswap", STATUS),
        Map.<String, MoveType>entry("heatcrash", DAMAGE),
        Map.<String, MoveType>entry("heatwave", DAMAGE),
        Map.<String, MoveType>entry("heavyslam", DAMAGE),
        Map.<String, MoveType>entry("helpinghand", BUFF),
        Map.<String, MoveType>entry("hex", DAMAGE),
        Map.<String, MoveType>entry("hiddenpower", DAMAGE),
        Map.<String, MoveType>entry("highhorsepower", DAMAGE),
        Map.<String, MoveType>entry("highjumpkick", DAMAGE),
        Map.<String, MoveType>entry("holdback", DAMAGE),
        Map.<String, MoveType>entry("holdhands", STATUS),
        Map.<String, MoveType>entry("honeclaws", BUFF),
        Map.<String, MoveType>entry("hornattack", DAMAGE),
        Map.<String, MoveType>entry("horndrill", DAMAGE),
        Map.<String, MoveType>entry("hornleech", DAMAGE),
        Map.<String, MoveType>entry("howl", BUFF),
        Map.<String, MoveType>entry("hurricane", DAMAGE),
        Map.<String, MoveType>entry("hydrocannon", DAMAGE),
        Map.<String, MoveType>entry("hydropump", DAMAGE),
        Map.<String, MoveType>entry("hydrosteam", DAMAGE),
        Map.<String, MoveType>entry("hydrovortex", DAMAGE),
        Map.<String, MoveType>entry("hyperbeam", DAMAGE),
        Map.<String, MoveType>entry("hyperdrill", DAMAGE),
        Map.<String, MoveType>entry("hyperfang", DAMAGE),
        Map.<String, MoveType>entry("hypervoice", DAMAGE),
        Map.<String, MoveType>entry("hyperspacefury", DAMAGE),
        Map.<String, MoveType>entry("hyperspacehole", DAMAGE),
        Map.<String, MoveType>entry("hypnosis", STATUS),
        Map.<String, MoveType>entry("iceball", DAMAGE),
        Map.<String, MoveType>entry("icebeam", DAMAGE),
        Map.<String, MoveType>entry("iceburn", DAMAGE),
        Map.<String, MoveType>entry("icefang", DAMAGE),
        Map.<String, MoveType>entry("icehammer", DAMAGE),
        Map.<String, MoveType>entry("icepunch", DAMAGE),
        Map.<String, MoveType>entry("iceshard", DAMAGE),
        Map.<String, MoveType>entry("icespinner", DAMAGE),
        Map.<String, MoveType>entry("iciclecrash", DAMAGE),
        Map.<String, MoveType>entry("iciclespear", DAMAGE),
        Map.<String, MoveType>entry("icywind", DAMAGE),
        Map.<String, MoveType>entry("imprison", STATUS),
        Map.<String, MoveType>entry("incinerate", DAMAGE),
        Map.<String, MoveType>entry("infernalparade", DAMAGE),
        Map.<String, MoveType>entry("inferno", DAMAGE),
        Map.<String, MoveType>entry("infernooverdrive", DAMAGE),
        Map.<String, MoveType>entry("infestation", DAMAGE),
        Map.<String, MoveType>entry("ingrain", HEAL),
        Map.<String, MoveType>entry("instruct", STATUS),
        Map.<String, MoveType>entry("iondeluge", STATUS),
        Map.<String, MoveType>entry("irondefense", BUFF),
        Map.<String, MoveType>entry("ironhead", DAMAGE),
        Map.<String, MoveType>entry("irontail", DAMAGE),
        Map.<String, MoveType>entry("ivycudgel", DAMAGE),
        Map.<String, MoveType>entry("jawlock", DAMAGE),
        Map.<String, MoveType>entry("jetpunch", DAMAGE),
        Map.<String, MoveType>entry("judgment", DAMAGE),
        Map.<String, MoveType>entry("jumpkick", DAMAGE),
        Map.<String, MoveType>entry("junglehealing", HEAL),
        Map.<String, MoveType>entry("karatechop", DAMAGE),
        Map.<String, MoveType>entry("kinesis", STATUS),
        Map.<String, MoveType>entry("kingsshield", STATUS),
        Map.<String, MoveType>entry("knockoff", DAMAGE),
        Map.<String, MoveType>entry("kowtowcleave", DAMAGE),
        Map.<String, MoveType>entry("landswrath", DAMAGE),
        Map.<String, MoveType>entry("laserfocus", BUFF),
        Map.<String, MoveType>entry("lashout", DAMAGE),
        Map.<String, MoveType>entry("lastresort", DAMAGE),
        Map.<String, MoveType>entry("lastrespects", DAMAGE),
        Map.<String, MoveType>entry("lavaplume", DAMAGE),
        Map.<String, MoveType>entry("leafblade", DAMAGE),
        Map.<String, MoveType>entry("leafstorm", DAMAGE),
        Map.<String, MoveType>entry("leaftornado", DAMAGE),
        Map.<String, MoveType>entry("leafage", DAMAGE),
        Map.<String, MoveType>entry("leechlife", DAMAGE),
        Map.<String, MoveType>entry("leechseed", STATUS),
        Map.<String, MoveType>entry("leer", MALUS),
        Map.<String, MoveType>entry("letssnuggleforever", DAMAGE),
        Map.<String, MoveType>entry("lick", DAMAGE),
        Map.<String, MoveType>entry("lifedew", HEAL),
        Map.<String, MoveType>entry("lightofruin", DAMAGE),
        Map.<String, MoveType>entry("lightscreen", BUFF),
        Map.<String, MoveType>entry("lightthatburnsthesky", DAMAGE),
        Map.<String, MoveType>entry("liquidation", DAMAGE),
        Map.<String, MoveType>entry("lockon", STATUS),
        Map.<String, MoveType>entry("lovelykiss", STATUS),
        Map.<String, MoveType>entry("lowkick", DAMAGE),
        Map.<String, MoveType>entry("lowsweep", DAMAGE),
        Map.<String, MoveType>entry("luckychant", STATUS),
        Map.<String, MoveType>entry("luminacrash", DAMAGE),
        Map.<String, MoveType>entry("lunarblessing", HEAL),
        Map.<String, MoveType>entry("lunardance", STATUS),
        Map.<String, MoveType>entry("lunge", DAMAGE),
        Map.<String, MoveType>entry("lusterpurge", DAMAGE),
        Map.<String, MoveType>entry("machpunch", DAMAGE),
        Map.<String, MoveType>entry("magiccoat", STATUS),
        Map.<String, MoveType>entry("magicpowder", STATUS),
        Map.<String, MoveType>entry("magicroom", STATUS),
        Map.<String, MoveType>entry("magicalleaf", DAMAGE),
        Map.<String, MoveType>entry("magicaltorque", DAMAGE),
        Map.<String, MoveType>entry("magmastorm", DAMAGE),
        Map.<String, MoveType>entry("magnetbomb", DAMAGE),
        Map.<String, MoveType>entry("magnetrise", STATUS),
        Map.<String, MoveType>entry("magneticflux", BUFF),
        Map.<String, MoveType>entry("magnitude", DAMAGE),
        Map.<String, MoveType>entry("makeitrain", DAMAGE),
        Map.<String, MoveType>entry("maliciousmoonsault", DAMAGE),
        Map.<String, MoveType>entry("malignantchain", DAMAGE),
        Map.<String, MoveType>entry("matblock", STATUS),
        Map.<String, MoveType>entry("matchagotcha", DAMAGE),
        Map.<String, MoveType>entry("maxairstream", DAMAGE),
        Map.<String, MoveType>entry("maxdarkness", DAMAGE),
        Map.<String, MoveType>entry("maxflare", DAMAGE),
        Map.<String, MoveType>entry("maxflutterby", DAMAGE),
        Map.<String, MoveType>entry("maxgeyser", DAMAGE),
        Map.<String, MoveType>entry("maxguard", DAMAGE),
        Map.<String, MoveType>entry("maxhailstorm", DAMAGE),
        Map.<String, MoveType>entry("maxknuckle", DAMAGE),
        Map.<String, MoveType>entry("maxlightning", DAMAGE),
        Map.<String, MoveType>entry("maxmindstorm", DAMAGE),
        Map.<String, MoveType>entry("maxooze", DAMAGE),
        Map.<String, MoveType>entry("maxovergrowth", DAMAGE),
        Map.<String, MoveType>entry("maxphantasm", DAMAGE),
        Map.<String, MoveType>entry("maxquake", DAMAGE),
        Map.<String, MoveType>entry("maxrockfall", DAMAGE),
        Map.<String, MoveType>entry("maxstarfall", DAMAGE),
        Map.<String, MoveType>entry("maxsteelspike", DAMAGE),
        Map.<String, MoveType>entry("maxstrike", DAMAGE),
        Map.<String, MoveType>entry("maxwyrmwind", DAMAGE),
        Map.<String, MoveType>entry("mefirst", STATUS),
        Map.<String, MoveType>entry("meanlook", STATUS),
        Map.<String, MoveType>entry("meditate", BUFF),
        Map.<String, MoveType>entry("megadrain", DAMAGE),
        Map.<String, MoveType>entry("megakick", DAMAGE),
        Map.<String, MoveType>entry("megapunch", DAMAGE),
        Map.<String, MoveType>entry("megahorn", DAMAGE),
        Map.<String, MoveType>entry("memento", STATUS),
        Map.<String, MoveType>entry("menacingmoonrazemaelstrom", DAMAGE),
        Map.<String, MoveType>entry("metalburst", DAMAGE),
        Map.<String, MoveType>entry("metalclaw", DAMAGE),
        Map.<String, MoveType>entry("metalsound", MALUS),
        Map.<String, MoveType>entry("meteorassault", DAMAGE),
        Map.<String, MoveType>entry("meteorbeam", DAMAGE),
        Map.<String, MoveType>entry("meteormash", DAMAGE),
        Map.<String, MoveType>entry("metronome", STATUS),
        Map.<String, MoveType>entry("mightycleave", DAMAGE),
        Map.<String, MoveType>entry("milkdrink", HEAL),
        Map.<String, MoveType>entry("mimic", STATUS),
        Map.<String, MoveType>entry("mindblown", DAMAGE),
        Map.<String, MoveType>entry("mindreader", STATUS),
        Map.<String, MoveType>entry("minimize", STATUS),
        Map.<String, MoveType>entry("miracleeye", STATUS),
        Map.<String, MoveType>entry("mirrorcoat", DAMAGE),
        Map.<String, MoveType>entry("mirrormove", STATUS),
        Map.<String, MoveType>entry("mirrorshot", DAMAGE),
        Map.<String, MoveType>entry("mist", STATUS),
        Map.<String, MoveType>entry("mistball", DAMAGE),
        Map.<String, MoveType>entry("mistyexplosion", DAMAGE),
        Map.<String, MoveType>entry("mistyterrain", STATUS),
        Map.<String, MoveType>entry("moonblast", DAMAGE),
        Map.<String, MoveType>entry("moongeistbeam", DAMAGE),
        Map.<String, MoveType>entry("moonlight", HEAL),
        Map.<String, MoveType>entry("morningsun", HEAL),
        Map.<String, MoveType>entry("mortalspin", DAMAGE),
        Map.<String, MoveType>entry("mountaingale", DAMAGE),
        Map.<String, MoveType>entry("mudbomb", DAMAGE),
        Map.<String, MoveType>entry("mudshot", DAMAGE),
        Map.<String, MoveType>entry("mudsport", STATUS),
        Map.<String, MoveType>entry("mudslap", DAMAGE),
        Map.<String, MoveType>entry("muddywater", DAMAGE),
        Map.<String, MoveType>entry("multiattack", DAMAGE),
        Map.<String, MoveType>entry("mysticalfire", DAMAGE),
        Map.<String, MoveType>entry("mysticalpower", DAMAGE),
        Map.<String, MoveType>entry("nastyplot", BUFF),
        Map.<String, MoveType>entry("naturalgift", DAMAGE),
        Map.<String, MoveType>entry("naturepower", STATUS),
        Map.<String, MoveType>entry("naturesmadness", DAMAGE),
        Map.<String, MoveType>entry("needlearm", DAMAGE),
        Map.<String, MoveType>entry("neverendingnightmare", DAMAGE),
        Map.<String, MoveType>entry("nightdaze", DAMAGE),
        Map.<String, MoveType>entry("nightshade", DAMAGE),
        Map.<String, MoveType>entry("nightslash", DAMAGE),
        Map.<String, MoveType>entry("nightmare", STATUS),
        Map.<String, MoveType>entry("noretreat", STATUS),
        Map.<String, MoveType>entry("nobleroar", MALUS),
        Map.<String, MoveType>entry("noxioustorque", DAMAGE),
        Map.<String, MoveType>entry("nuzzle", DAMAGE),
        Map.<String, MoveType>entry("oblivionwing", DAMAGE),
        Map.<String, MoveType>entry("obstruct", STATUS),
        Map.<String, MoveType>entry("oceanicoperetta", DAMAGE),
        Map.<String, MoveType>entry("octazooka", DAMAGE),
        Map.<String, MoveType>entry("octolock", STATUS),
        Map.<String, MoveType>entry("odorsleuth", STATUS),
        Map.<String, MoveType>entry("ominouswind", DAMAGE),
        Map.<String, MoveType>entry("orderup", DAMAGE),
        Map.<String, MoveType>entry("originpulse", DAMAGE),
        Map.<String, MoveType>entry("outrage", DAMAGE),
        Map.<String, MoveType>entry("overdrive", DAMAGE),
        Map.<String, MoveType>entry("overheat", DAMAGE),
        Map.<String, MoveType>entry("painsplit", STATUS),
        Map.<String, MoveType>entry("paraboliccharge", DAMAGE),
        Map.<String, MoveType>entry("partingshot", MALUS),
        Map.<String, MoveType>entry("payday", DAMAGE),
        Map.<String, MoveType>entry("payback", DAMAGE),
        Map.<String, MoveType>entry("peck", DAMAGE),
        Map.<String, MoveType>entry("perishsong", STATUS),
        Map.<String, MoveType>entry("petalblizzard", DAMAGE),
        Map.<String, MoveType>entry("petaldance", DAMAGE),
        Map.<String, MoveType>entry("phantomforce", DAMAGE),
        Map.<String, MoveType>entry("photongeyser", DAMAGE),
        Map.<String, MoveType>entry("pikapapow", DAMAGE),
        Map.<String, MoveType>entry("pinmissile", DAMAGE),
        Map.<String, MoveType>entry("plasmafists", DAMAGE),
        Map.<String, MoveType>entry("playnice", MALUS),
        Map.<String, MoveType>entry("playrough", DAMAGE),
        Map.<String, MoveType>entry("pluck", DAMAGE),
        Map.<String, MoveType>entry("poisonfang", DAMAGE),
        Map.<String, MoveType>entry("poisongas", STATUS),
        Map.<String, MoveType>entry("poisonjab", DAMAGE),
        Map.<String, MoveType>entry("poisonpowder", STATUS),
        Map.<String, MoveType>entry("poisonsting", DAMAGE),
        Map.<String, MoveType>entry("poisontail", DAMAGE),
        Map.<String, MoveType>entry("pollenpuff", DAMAGE),
        Map.<String, MoveType>entry("poltergeist", DAMAGE),
        Map.<String, MoveType>entry("populationbomb", DAMAGE),
        Map.<String, MoveType>entry("pounce", DAMAGE),
        Map.<String, MoveType>entry("pound", DAMAGE),
        Map.<String, MoveType>entry("powder", STATUS),
        Map.<String, MoveType>entry("powdersnow", DAMAGE),
        Map.<String, MoveType>entry("powergem", DAMAGE),
        Map.<String, MoveType>entry("powershift", STATUS),
        Map.<String, MoveType>entry("powersplit", STATUS),
        Map.<String, MoveType>entry("powerswap", STATUS),
        Map.<String, MoveType>entry("powertrick", STATUS),
        Map.<String, MoveType>entry("powertrip", DAMAGE),
        Map.<String, MoveType>entry("powerwhip", DAMAGE),
        Map.<String, MoveType>entry("poweruppunch", DAMAGE),
        Map.<String, MoveType>entry("precipiceblades", DAMAGE),
        Map.<String, MoveType>entry("present", DAMAGE),
        Map.<String, MoveType>entry("prismaticlaser", DAMAGE),
        Map.<String, MoveType>entry("protect", STATUS),
        Map.<String, MoveType>entry("psybeam", DAMAGE),
        Map.<String, MoveType>entry("psyblade", DAMAGE),
        Map.<String, MoveType>entry("psychup", STATUS),
        Map.<String, MoveType>entry("psychic", DAMAGE),
        Map.<String, MoveType>entry("psychicfangs", DAMAGE),
        Map.<String, MoveType>entry("psychicnoise", DAMAGE),
        Map.<String, MoveType>entry("psychicterrain", STATUS),
        Map.<String, MoveType>entry("psychoboost", DAMAGE),
        Map.<String, MoveType>entry("psychocut", DAMAGE),
        Map.<String, MoveType>entry("psychoshift", CURE),
        Map.<String, MoveType>entry("psyshieldbash", DAMAGE),
        Map.<String, MoveType>entry("psyshock", DAMAGE),
        Map.<String, MoveType>entry("psystrike", DAMAGE),
        Map.<String, MoveType>entry("psywave", DAMAGE),
        Map.<String, MoveType>entry("pulverizingpancake", DAMAGE),
        Map.<String, MoveType>entry("punishment", DAMAGE),
        Map.<String, MoveType>entry("purify", CURE),
        Map.<String, MoveType>entry("pursuit", DAMAGE),
        Map.<String, MoveType>entry("pyroball", DAMAGE),
        Map.<String, MoveType>entry("quash", STATUS),
        Map.<String, MoveType>entry("quickattack", DAMAGE),
        Map.<String, MoveType>entry("quickguard", STATUS),
        Map.<String, MoveType>entry("quiverdance", BUFF),
        Map.<String, MoveType>entry("rage", DAMAGE),
        Map.<String, MoveType>entry("ragefist", DAMAGE),
        Map.<String, MoveType>entry("ragepowder", STATUS),
        Map.<String, MoveType>entry("ragingbull", DAMAGE),
        Map.<String, MoveType>entry("ragingfury", DAMAGE),
        Map.<String, MoveType>entry("raindance", STATUS),
        Map.<String, MoveType>entry("rapidspin", DAMAGE),
        Map.<String, MoveType>entry("razorleaf", DAMAGE),
        Map.<String, MoveType>entry("razorshell", DAMAGE),
        Map.<String, MoveType>entry("razorwind", DAMAGE),
        Map.<String, MoveType>entry("recover", HEAL),
        Map.<String, MoveType>entry("recycle", STATUS),
        Map.<String, MoveType>entry("reflect", BUFF),
        Map.<String, MoveType>entry("reflecttype", STATUS),
        Map.<String, MoveType>entry("refresh", HEAL),
        Map.<String, MoveType>entry("relicsong", DAMAGE),
        Map.<String, MoveType>entry("rest", HEAL),
        Map.<String, MoveType>entry("retaliate", DAMAGE),
        Map.<String, MoveType>entry("return", DAMAGE),
        Map.<String, MoveType>entry("revelationdance", DAMAGE),
        Map.<String, MoveType>entry("revenge", DAMAGE),
        Map.<String, MoveType>entry("reversal", DAMAGE),
        Map.<String, MoveType>entry("revivalblessing", HEAL),
        Map.<String, MoveType>entry("risingvoltage", DAMAGE),
        Map.<String, MoveType>entry("roar", STATUS),
        Map.<String, MoveType>entry("roaroftime", DAMAGE),
        Map.<String, MoveType>entry("rockblast", DAMAGE),
        Map.<String, MoveType>entry("rockclimb", DAMAGE),
        Map.<String, MoveType>entry("rockpolish", BUFF),
        Map.<String, MoveType>entry("rockslide", DAMAGE),
        Map.<String, MoveType>entry("rocksmash", DAMAGE),
        Map.<String, MoveType>entry("rockthrow", DAMAGE),
        Map.<String, MoveType>entry("rocktomb", DAMAGE),
        Map.<String, MoveType>entry("rockwrecker", DAMAGE),
        Map.<String, MoveType>entry("roleplay", STATUS),
        Map.<String, MoveType>entry("rollingkick", DAMAGE),
        Map.<String, MoveType>entry("rollout", DAMAGE),
        Map.<String, MoveType>entry("roost", HEAL),
        Map.<String, MoveType>entry("rototiller", STATUS),
        Map.<String, MoveType>entry("round", DAMAGE),
        Map.<String, MoveType>entry("ruination", DAMAGE),
        Map.<String, MoveType>entry("sacredfire", DAMAGE),
        Map.<String, MoveType>entry("sacredsword", DAMAGE),
        Map.<String, MoveType>entry("safeguard", STATUS),
        Map.<String, MoveType>entry("saltcure", DAMAGE),
        Map.<String, MoveType>entry("sandattack", MALUS),
        Map.<String, MoveType>entry("sandtomb", DAMAGE),
        Map.<String, MoveType>entry("sandsearstorm", DAMAGE),
        Map.<String, MoveType>entry("sandstorm", STATUS),
        Map.<String, MoveType>entry("sappyseed", DAMAGE),
        Map.<String, MoveType>entry("savagespinout", DAMAGE),
        Map.<String, MoveType>entry("scald", DAMAGE),
        Map.<String, MoveType>entry("scaleshot", DAMAGE),
        Map.<String, MoveType>entry("scaryface", MALUS),
        Map.<String, MoveType>entry("scorchingsands", DAMAGE),
        Map.<String, MoveType>entry("scratch", DAMAGE),
        Map.<String, MoveType>entry("screech", MALUS),
        Map.<String, MoveType>entry("searingshot", DAMAGE),
        Map.<String, MoveType>entry("searingsunrazesmash", DAMAGE),
        Map.<String, MoveType>entry("secretpower", DAMAGE),
        Map.<String, MoveType>entry("secretsword", DAMAGE),
        Map.<String, MoveType>entry("seedbomb", DAMAGE),
        Map.<String, MoveType>entry("seedflare", DAMAGE),
        Map.<String, MoveType>entry("seismictoss", DAMAGE),
        Map.<String, MoveType>entry("selfdestruct", DAMAGE),
        Map.<String, MoveType>entry("shadowball", DAMAGE),
        Map.<String, MoveType>entry("shadowbone", DAMAGE),
        Map.<String, MoveType>entry("shadowclaw", DAMAGE),
        Map.<String, MoveType>entry("shadowforce", DAMAGE),
        Map.<String, MoveType>entry("shadowpunch", DAMAGE),
        Map.<String, MoveType>entry("shadowsneak", DAMAGE),
        Map.<String, MoveType>entry("sharpen", BUFF),
        Map.<String, MoveType>entry("shatteredpsyche", DAMAGE),
        Map.<String, MoveType>entry("shedtail", STATUS),
        Map.<String, MoveType>entry("sheercold", DAMAGE),
        Map.<String, MoveType>entry("shellsidearm", DAMAGE),
        Map.<String, MoveType>entry("shellsmash", BUFF),
        Map.<String, MoveType>entry("shelltrap", DAMAGE),
        Map.<String, MoveType>entry("shelter", STATUS),
        Map.<String, MoveType>entry("shiftgear", BUFF),
        Map.<String, MoveType>entry("shockwave", DAMAGE),
        Map.<String, MoveType>entry("shoreup", HEAL),
        Map.<String, MoveType>entry("signalbeam", DAMAGE),
        Map.<String, MoveType>entry("silktrap", STATUS),
        Map.<String, MoveType>entry("silverwind", DAMAGE),
        Map.<String, MoveType>entry("simplebeam", STATUS),
        Map.<String, MoveType>entry("sing", STATUS),
        Map.<String, MoveType>entry("sinisterarrowraid", DAMAGE),
        Map.<String, MoveType>entry("sizzlyslide", DAMAGE),
        Map.<String, MoveType>entry("sketch", STATUS),
        Map.<String, MoveType>entry("skillswap", STATUS),
        Map.<String, MoveType>entry("skittersmack", DAMAGE),
        Map.<String, MoveType>entry("skullbash", DAMAGE),
        Map.<String, MoveType>entry("skyattack", DAMAGE),
        Map.<String, MoveType>entry("skydrop", DAMAGE),
        Map.<String, MoveType>entry("skyuppercut", DAMAGE),
        Map.<String, MoveType>entry("slackoff", HEAL),
        Map.<String, MoveType>entry("slam", DAMAGE),
        Map.<String, MoveType>entry("slash", DAMAGE),
        Map.<String, MoveType>entry("sleeppowder", STATUS),
        Map.<String, MoveType>entry("sleeptalk", STATUS),
        Map.<String, MoveType>entry("sludge", DAMAGE),
        Map.<String, MoveType>entry("sludgebomb", DAMAGE),
        Map.<String, MoveType>entry("sludgewave", DAMAGE),
        Map.<String, MoveType>entry("smackdown", DAMAGE),
        Map.<String, MoveType>entry("smartstrike", DAMAGE),
        Map.<String, MoveType>entry("smellingsalts", DAMAGE),
        Map.<String, MoveType>entry("smog", DAMAGE),
        Map.<String, MoveType>entry("smokescreen", MALUS),
        Map.<String, MoveType>entry("snaptrap", DAMAGE),
        Map.<String, MoveType>entry("snarl", DAMAGE),
        Map.<String, MoveType>entry("snatch", STATUS),
        Map.<String, MoveType>entry("snipeshot", DAMAGE),
        Map.<String, MoveType>entry("snore", DAMAGE),
        Map.<String, MoveType>entry("snowscape", STATUS),
        Map.<String, MoveType>entry("soak", STATUS),
        Map.<String, MoveType>entry("softboiled", HEAL),
        Map.<String, MoveType>entry("solarbeam", DAMAGE),
        Map.<String, MoveType>entry("solarblade", DAMAGE),
        Map.<String, MoveType>entry("sonicboom", DAMAGE),
        Map.<String, MoveType>entry("soulstealing7starstrike", DAMAGE),
        Map.<String, MoveType>entry("spacialrend", DAMAGE),
        Map.<String, MoveType>entry("spark", DAMAGE),
        Map.<String, MoveType>entry("sparklingaria", DAMAGE),
        Map.<String, MoveType>entry("sparklyswirl", DAMAGE),
        Map.<String, MoveType>entry("spectralthief", DAMAGE),
        Map.<String, MoveType>entry("speedswap", STATUS),
        Map.<String, MoveType>entry("spicyextract", BUFF),
        Map.<String, MoveType>entry("spiderweb", STATUS),
        Map.<String, MoveType>entry("spikecannon", DAMAGE),
        Map.<String, MoveType>entry("spikes", STATUS),
        Map.<String, MoveType>entry("spikyshield", STATUS),
        Map.<String, MoveType>entry("spinout", DAMAGE),
        Map.<String, MoveType>entry("spiritbreak", DAMAGE),
        Map.<String, MoveType>entry("spiritshackle", DAMAGE),
        Map.<String, MoveType>entry("spitup", DAMAGE),
        Map.<String, MoveType>entry("spite", STATUS),
        Map.<String, MoveType>entry("splash", STATUS),
        Map.<String, MoveType>entry("splinteredstormshards", DAMAGE),
        Map.<String, MoveType>entry("splishysplash", DAMAGE),
        Map.<String, MoveType>entry("spore", STATUS),
        Map.<String, MoveType>entry("spotlight", STATUS),
        Map.<String, MoveType>entry("springtidestorm", DAMAGE),
        Map.<String, MoveType>entry("stealthrock", STATUS),
        Map.<String, MoveType>entry("steameruption", DAMAGE),
        Map.<String, MoveType>entry("steamroller", DAMAGE),
        Map.<String, MoveType>entry("steelbeam", DAMAGE),
        Map.<String, MoveType>entry("steelroller", DAMAGE),
        Map.<String, MoveType>entry("steelwing", DAMAGE),
        Map.<String, MoveType>entry("stickyweb", STATUS),
        Map.<String, MoveType>entry("stockpile", BUFF),
        Map.<String, MoveType>entry("stokedsparksurfer", DAMAGE),
        Map.<String, MoveType>entry("stomp", DAMAGE),
        Map.<String, MoveType>entry("stompingtantrum", DAMAGE),
        Map.<String, MoveType>entry("stoneaxe", DAMAGE),
        Map.<String, MoveType>entry("stoneedge", DAMAGE),
        Map.<String, MoveType>entry("storedpower", DAMAGE),
        Map.<String, MoveType>entry("stormthrow", DAMAGE),
        Map.<String, MoveType>entry("strangesteam", DAMAGE),
        Map.<String, MoveType>entry("strength", DAMAGE),
        Map.<String, MoveType>entry("strengthsap", HEAL),
        Map.<String, MoveType>entry("stringshot", STATUS),
        Map.<String, MoveType>entry("struggle", DAMAGE),
        Map.<String, MoveType>entry("strugglebug", DAMAGE),
        Map.<String, MoveType>entry("stuffcheeks", STATUS),
        Map.<String, MoveType>entry("stunspore", STATUS),
        Map.<String, MoveType>entry("submission", DAMAGE),
        Map.<String, MoveType>entry("substitute", STATUS),
        Map.<String, MoveType>entry("subzeroslammer", DAMAGE),
        Map.<String, MoveType>entry("suckerpunch", DAMAGE),
        Map.<String, MoveType>entry("sunnyday", STATUS),
        Map.<String, MoveType>entry("sunsteelstrike", DAMAGE),
        Map.<String, MoveType>entry("superfang", DAMAGE),
        Map.<String, MoveType>entry("supercellslam", DAMAGE),
        Map.<String, MoveType>entry("superpower", DAMAGE),
        Map.<String, MoveType>entry("supersonic", STATUS),
        Map.<String, MoveType>entry("supersonicskystrike", DAMAGE),
        Map.<String, MoveType>entry("surf", DAMAGE),
        Map.<String, MoveType>entry("surgingstrikes", DAMAGE),
        Map.<String, MoveType>entry("swagger", MALUS),
        Map.<String, MoveType>entry("swallow", STATUS),
        Map.<String, MoveType>entry("sweetkiss", STATUS),
        Map.<String, MoveType>entry("sweetscent", STATUS),
        Map.<String, MoveType>entry("swift", DAMAGE),
        Map.<String, MoveType>entry("switcheroo", STATUS),
        Map.<String, MoveType>entry("swordsdance", BUFF),
        Map.<String, MoveType>entry("synchronoise", DAMAGE),
        Map.<String, MoveType>entry("synthesis", HEAL),
        Map.<String, MoveType>entry("syrupbomb", DAMAGE),
        Map.<String, MoveType>entry("tachyoncutter", DAMAGE),
        Map.<String, MoveType>entry("tackle", DAMAGE),
        Map.<String, MoveType>entry("tailglow", BUFF),
        Map.<String, MoveType>entry("tailslap", DAMAGE),
        Map.<String, MoveType>entry("tailwhip", MALUS),
        Map.<String, MoveType>entry("tailwind", BUFF),
        Map.<String, MoveType>entry("takedown", DAMAGE),
        Map.<String, MoveType>entry("takeheart", BUFF),
        Map.<String, MoveType>entry("tarshot", MALUS),
        Map.<String, MoveType>entry("taunt", STATUS),
        Map.<String, MoveType>entry("tearfullook", MALUS),
        Map.<String, MoveType>entry("teatime", STATUS),
        Map.<String, MoveType>entry("technoblast", DAMAGE),
        Map.<String, MoveType>entry("tectonicrage", DAMAGE),
        Map.<String, MoveType>entry("teeterdance", STATUS),
        Map.<String, MoveType>entry("telekinesis", STATUS),
        Map.<String, MoveType>entry("teleport", STATUS),
        Map.<String, MoveType>entry("temperflare", DAMAGE),
        Map.<String, MoveType>entry("terablast", DAMAGE),
        Map.<String, MoveType>entry("terastarstorm", DAMAGE),
        Map.<String, MoveType>entry("terrainpulse", DAMAGE),
        Map.<String, MoveType>entry("thief", DAMAGE),
        Map.<String, MoveType>entry("thousandarrows", DAMAGE),
        Map.<String, MoveType>entry("thousandwaves", DAMAGE),
        Map.<String, MoveType>entry("thrash", DAMAGE),
        Map.<String, MoveType>entry("throatchop", DAMAGE),
        Map.<String, MoveType>entry("thunder", DAMAGE),
        Map.<String, MoveType>entry("thundercage", DAMAGE),
        Map.<String, MoveType>entry("thunderfang", DAMAGE),
        Map.<String, MoveType>entry("thunderpunch", DAMAGE),
        Map.<String, MoveType>entry("thundershock", DAMAGE),
        Map.<String, MoveType>entry("thunderwave", STATUS),
        Map.<String, MoveType>entry("thunderbolt", DAMAGE),
        Map.<String, MoveType>entry("thunderclap", DAMAGE),
        Map.<String, MoveType>entry("thunderouskick", DAMAGE),
        Map.<String, MoveType>entry("tickle", MALUS),
        Map.<String, MoveType>entry("tidyup", STATUS),
        Map.<String, MoveType>entry("topsyturvy", MALUS),
        Map.<String, MoveType>entry("torchsong", DAMAGE),
        Map.<String, MoveType>entry("torment", STATUS),
        Map.<String, MoveType>entry("toxic", STATUS),
        Map.<String, MoveType>entry("toxicspikes", STATUS),
        Map.<String, MoveType>entry("toxicthread", STATUS),
        Map.<String, MoveType>entry("trailblaze", DAMAGE),
        Map.<String, MoveType>entry("transform", STATUS),
        Map.<String, MoveType>entry("triattack", DAMAGE),
        Map.<String, MoveType>entry("trick", STATUS),
        Map.<String, MoveType>entry("trickroom", STATUS),
        Map.<String, MoveType>entry("trickortreat", STATUS),
        Map.<String, MoveType>entry("triplearrows", DAMAGE),
        Map.<String, MoveType>entry("tripleaxel", DAMAGE),
        Map.<String, MoveType>entry("tripledive", DAMAGE),
        Map.<String, MoveType>entry("triplekick", DAMAGE),
        Map.<String, MoveType>entry("tropkick", DAMAGE),
        Map.<String, MoveType>entry("trumpcard", DAMAGE),
        Map.<String, MoveType>entry("twinbeam", DAMAGE),
        Map.<String, MoveType>entry("twineedle", DAMAGE),
        Map.<String, MoveType>entry("twinkletackle", DAMAGE),
        Map.<String, MoveType>entry("twister", DAMAGE),
        Map.<String, MoveType>entry("uturn", DAMAGE),
        Map.<String, MoveType>entry("upperhand", DAMAGE),
        Map.<String, MoveType>entry("uproar", DAMAGE),
        Map.<String, MoveType>entry("vcreate", DAMAGE),
        Map.<String, MoveType>entry("vacuumwave", DAMAGE),
        Map.<String, MoveType>entry("veeveevolley", DAMAGE),
        Map.<String, MoveType>entry("venomdrench", MALUS),
        Map.<String, MoveType>entry("venoshock", DAMAGE),
        Map.<String, MoveType>entry("victorydance", BUFF),
        Map.<String, MoveType>entry("vinewhip", DAMAGE),
        Map.<String, MoveType>entry("visegrip", DAMAGE),
        Map.<String, MoveType>entry("vitalthrow", DAMAGE),
        Map.<String, MoveType>entry("voltswitch", DAMAGE),
        Map.<String, MoveType>entry("volttackle", DAMAGE),
        Map.<String, MoveType>entry("wakeupslap", DAMAGE),
        Map.<String, MoveType>entry("watergun", DAMAGE),
        Map.<String, MoveType>entry("waterpledge", DAMAGE),
        Map.<String, MoveType>entry("waterpulse", DAMAGE),
        Map.<String, MoveType>entry("watershuriken", DAMAGE),
        Map.<String, MoveType>entry("watersport", STATUS),
        Map.<String, MoveType>entry("waterspout", DAMAGE),
        Map.<String, MoveType>entry("waterfall", DAMAGE),
        Map.<String, MoveType>entry("wavecrash", DAMAGE),
        Map.<String, MoveType>entry("weatherball", DAMAGE),
        Map.<String, MoveType>entry("whirlpool", DAMAGE),
        Map.<String, MoveType>entry("whirlwind", STATUS),
        Map.<String, MoveType>entry("wickedblow", DAMAGE),
        Map.<String, MoveType>entry("wickedtorque", DAMAGE),
        Map.<String, MoveType>entry("wideguard", STATUS),
        Map.<String, MoveType>entry("wildcharge", DAMAGE),
        Map.<String, MoveType>entry("wildboltstorm", DAMAGE),
        Map.<String, MoveType>entry("willowisp", STATUS),
        Map.<String, MoveType>entry("wingattack", DAMAGE),
        Map.<String, MoveType>entry("wish", HEAL),
        Map.<String, MoveType>entry("withdraw", STATUS),
        Map.<String, MoveType>entry("wonderroom", STATUS),
        Map.<String, MoveType>entry("woodhammer", DAMAGE),
        Map.<String, MoveType>entry("workup", BUFF),
        Map.<String, MoveType>entry("worryseed", STATUS),
        Map.<String, MoveType>entry("wrap", DAMAGE),
        Map.<String, MoveType>entry("wringout", DAMAGE),
        Map.<String, MoveType>entry("xscissor", DAMAGE),
        Map.<String, MoveType>entry("yawn", STATUS),
        Map.<String, MoveType>entry("zapcannon", DAMAGE),
        Map.<String, MoveType>entry("zenheadbutt", DAMAGE),
        Map.<String, MoveType>entry("zingzap", DAMAGE),
        Map.<String, MoveType>entry("zippyzap", DAMAGE)
    );
}
